const ALLOWED_RISKS=new Set(['A0','A1','A2']);
const ALLOWED_BACKENDS=new Set(['self-hosted','copilot']);
const sectionKey=(value='')=>String(value).trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const clean=(value='')=>String(value||'').replace(/^[-*+]\s+/,'').replace(/^\d+[.)]\s+/,'').trim();
const labelsOf=(issue)=>new Set((issue?.labels||[]).map(x=>typeof x==='string'?x:x?.name).filter(Boolean));

export function parseMissionPacket(body='',title=''){
  const fields={};const sections={};let current=null;
  for(const raw of String(body||'').split(/\r?\n/)){
    const heading=raw.match(/^###\s+(.+?)\s*$/);
    if(heading){current=sectionKey(heading[1]);sections[current]=sections[current]||[];continue}
    const field=raw.match(/^([A-Z][A-Z0-9_]+):\s*(.*?)\s*$/);
    if(field&&!current){fields[field[1].toLowerCase()]=field[2];continue}
    if(current)sections[current].push(raw);
  }
  const text=(key)=>(sections[key]||[]).map(x=>x.trim()).filter(Boolean).join(' ').trim();
  const list=(key)=>(sections[key]||[]).map(clean).filter(Boolean);
  return {
    title:String(title||''),
    approval:String(fields.approval||'').toLowerCase(),
    project:String(fields.project||''),
    repository:String(fields.repository||''),
    riskClass:String(fields.risk_class||'').toUpperCase(),
    runnerMode:String(fields.runner_mode||'auto').toLowerCase(),
    runnerBackend:String(fields.runner_backend||'self-hosted').toLowerCase(),
    snapshot:String(fields.snapshot||''),
    mission:text('approved_mission'),
    whyNow:text('why_now'),
    doneWhen:list('done_when'),
    constraints:list('constraints'),
    forbidden:list('forbidden'),
    executionBoundary:text('execution_boundary')
  };
}

export function validateMissionPacket(packet,{owner='mikelninh'}={}){
  const errors=[];
  if(packet.approval!=='approved')errors.push('APPROVAL must be approved');
  if(!packet.project)errors.push('PROJECT is required');
  if(!new RegExp(`^${owner.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\/[A-Za-z0-9._-]+$`).test(packet.repository))errors.push(`REPOSITORY must stay inside ${owner}/*`);
  if(!ALLOWED_RISKS.has(packet.riskClass))errors.push('Only A0-A2 missions may enter the automatic runner');
  if(!packet.mission)errors.push('Approved mission text is required');
  if(!packet.doneWhen.length)errors.push('At least one done-when criterion is required');
  if(!packet.constraints.length)errors.push('At least one constraint is required');
  if(!packet.forbidden.length)errors.push('At least one forbidden action is required');
  if(!/A0[–-]A2/.test(packet.executionBoundary))errors.push('Execution boundary must explicitly preserve A0-A2');
  if(!['auto','dry-run'].includes(packet.runnerMode))errors.push('RUNNER_MODE must be auto or dry-run');
  if(!ALLOWED_BACKENDS.has(packet.runnerBackend))errors.push(`RUNNER_BACKEND must be one of: ${[...ALLOWED_BACKENDS].join(', ')}`);
  return {ok:errors.length===0,errors};
}

export function assertMissionPacket(packet,options){const result=validateMissionPacket(packet,options);if(!result.ok)throw new Error(result.errors.join('; '));return packet}
export function sourceMarker(sourceRepo,issueNumber){return `<!-- council-mission:${sourceRepo}#${issueNumber} -->`}
export function targetMarker(targetRepo,issueNumber){return `<!-- runner-target:${targetRepo}#${issueNumber} -->`}
export function backendLabel(backend='self-hosted'){return `backend-${String(backend).replace(/[^a-z0-9-]+/g,'-')}`}

export function buildRunnerIssueBody(packet,{sourceRepo,sourceIssueNumber,sourceIssueUrl,backend=packet.runnerBackend||'self-hosted'}){
  return [sourceMarker(sourceRepo,sourceIssueNumber),'## Mission Control runner contract','',`SOURCE: ${sourceRepo}#${sourceIssueNumber}`,`SOURCE_URL: ${sourceIssueUrl}`,`PROJECT: ${packet.project}`,`RISK_CLASS: ${packet.riskClass}`,`RUNNER_BACKEND: ${backend}`,'','### Mission',packet.mission,'','### Why now',packet.whyNow||'Use the source mission packet as the rationale.','','### Done when',...packet.doneWhen.map(x=>`- ${x}`),'','### Constraints',...packet.constraints.map(x=>`- ${x}`),'','### Forbidden',...packet.forbidden.map(x=>`- ${x}`),'','### Runner protocol','1. **Scout** — read `AGENTS.md`, `.harness/`, current code/tests and existing evidence before changing anything.','2. **Builder** — implement the smallest reversible change that satisfies this mission.','3. **Verifier** — run the repository-owned tests/evals and independently check the claim. Never weaken a gate to make it pass.','4. **Chief handoff** — open a PR with Scout evidence, Builder changes, Verifier results, remaining uncertainty and the source Mission Control issue.','','### Authority','This runner is authorized only for A0–A2 work. Do not deploy, publish, send externally, spend money, access production/sensitive data, change secrets, merge the PR, or perform any A3/A4 action. Stop and report the gate instead.','','_Generated by Mission Control v1.2. Worker providers are replaceable; this contract is not._'].join('\n');
}

export function buildWorkerInstructions(packet,{sourceIssueUrl,targetIssueUrl='',backend=packet.runnerBackend||'self-hosted'}={}){
  return `You are a bounded Mission Control worker for ${packet.project}. Provider: ${backend}. Treat ${targetIssueUrl||'the target runner issue'} and ${sourceIssueUrl} as the binding mission contract. Read AGENTS.md, .harness/project.json, .harness/active-task.json and .harness/HANDOFF.md first when present. Work in explicit Scout -> Builder -> Verifier order. Reuse existing evidence before creating new machinery. Keep changes minimal and reversible. Run repository-owned verification from .harness/project.json and do not weaken safety/readiness checks. Record failures and remaining uncertainty. Open a PR; do not merge it. Never deploy, publish, send externally, spend, access secrets or sensitive/production data, or take any A3/A4 action. If the mission requires one, stop and state the exact human gate.`;
}

// Compatibility adapter for the optional paid GitHub backend. The contract remains provider-neutral.
export function buildCopilotInstructions(packet,options){return buildWorkerInstructions(packet,{...options,backend:'copilot'})}

export function runnerStatusFromLabels(labels=[]){
  const set=new Set(labels.map(x=>typeof x==='string'?x:x?.name).filter(Boolean));
  if(set.has('mission-complete'))return 'complete';
  if(set.has('runner-blocked')||set.has('worker-blocked'))return 'blocked';
  if(set.has('worker-review')||set.has('agent-review'))return 'review';
  if(set.has('worker-running')||set.has('agent-running'))return 'working';
  if(set.has('runner-queued')||set.has('agent-handoff'))return 'queued';
  if(set.has('runner-ready'))return 'ready';
  if(set.has('mission-approved'))return 'accepted';
  return 'none';
}

export function summarizeMissionIssues(issues=[]){
  const missions=(issues||[]).filter(x=>!x?.pull_request&&/^\[Mission\]/.test(x?.title||'')).map(issue=>{const packet=parseMissionPacket(issue.body||'',issue.title||'');return {issueNumber:issue.number,title:issue.title,url:issue.html_url||null,project:packet.project||null,repository:packet.repository||null,backend:packet.runnerBackend||'self-hosted',status:runnerStatusFromLabels(issue.labels||[]),updatedAt:issue.updated_at||issue.created_at||null,state:issue.state||'open'}}).sort((a,b)=>Date.parse(b.updatedAt||0)-Date.parse(a.updatedAt||0));
  const count=(status)=>missions.filter(x=>x.status===status).length;
  return {schema:'council-runner-summary-v1.2',counts:{working:count('working'),review:count('review'),blocked:count('blocked'),queued:count('queued'),complete:count('complete'),ready:count('ready')},active:missions.filter(x=>['working','review','blocked','queued'].includes(x.status)).slice(0,6),latestComplete:missions.find(x=>x.status==='complete')||null,latest:missions[0]||null};
}

export function issueHasLabel(issue,name){return labelsOf(issue).has(name)}
