import fs from 'node:fs';
import path from 'node:path';
import { deriveProjectState } from '../lib/mission-control.mjs';

const API='https://api.github.com';
const owner=process.env.GITHUB_USERNAME||'mikelninh';
const token=process.env.GITHUB_TOKEN||'';
const outDir=path.resolve(process.env.MISSION_CONTROL_OUTPUT||'dist-pages');
const refreshUrl=process.env.MISSION_CONTROL_REFRESH_URL||'https://github.com/mikelninh/council/actions';
const maxProjects=Math.max(8,Math.min(24,Number(process.env.MISSION_CONTROL_LIMIT||18)));
const corePriority=(process.env.MISSION_CONTROL_PUBLIC_PRIORITY||'trustready,digital-worker-factory,pruefpilot,care-os,gitlaw,citizen-agents,council').split(',').map(x=>x.trim()).filter(Boolean);
const baseHeaders={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10','User-Agent':'Council-GitHub-Pages-Mission-Control'};
async function request(pathname,{allow404=false}={}){const attempts=token?[true,false]:[false];let lastError=null;for(const authenticated of attempts){const response=await fetch(`${API}${pathname}`,{headers:{...baseHeaders,...(authenticated?{Authorization:`Bearer ${token}`}:{})}});if(response.status===404&&allow404)return null;if(response.ok)return response.json();const body=await response.json().catch(()=>({}));lastError=new Error(body?.message||`GitHub ${response.status}`);lastError.status=response.status;if(authenticated&&[401,403,404].includes(response.status))continue;break}throw lastError||new Error('GitHub request failed')}
async function rawText(repo,file){if(repo.name==='council'&&fs.existsSync(path.resolve(file)))return fs.readFileSync(path.resolve(file),'utf8');const ref=encodeURIComponent(repo.defaultBranch||'main'),target=file.split('/').map(encodeURIComponent).join('/');const response=await fetch(`https://raw.githubusercontent.com/${repo.fullName}/${ref}/${target}`,{headers:{'User-Agent':'Council-Mission-Control'}});if(response.status===404)return null;if(!response.ok)throw new Error(`raw ${response.status} ${repo.fullName}/${file}`);return response.text()}
async function readJson(repo,file){const text=await rawText(repo,file);if(!text)return null;try{return JSON.parse(text)}catch{return null}}
async function listPublicRepos(){const repos=[];for(let page=1;page<=3;page++){const rows=await request(`/users/${encodeURIComponent(owner)}/repos?per_page=100&page=${page}&type=owner&sort=pushed&direction=desc`);repos.push(...(Array.isArray(rows)?rows:[]));if(!Array.isArray(rows)||rows.length<100)break}return repos.filter(r=>!r.private&&!r.archived&&!r.fork)}
function daysSince(value){if(!value)return null;return Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000))}
function normalize(repo){return {name:repo.name,fullName:repo.full_name,url:repo.html_url,private:false,pushedAt:repo.pushed_at,daysSincePush:daysSince(repo.pushed_at),size:Number(repo.size||0),archived:Boolean(repo.archived),description:repo.description||'',defaultBranch:repo.default_branch||'main'}}
async function mapLimit(items,limit,worker){const output=new Array(items.length);let cursor=0;const runners=Array.from({length:Math.min(limit,items.length)},async()=>{while(true){const i=cursor++;if(i>=items.length)return;output[i]=await worker(items[i],i)}});await Promise.all(runners);return output}
const clean=(line='')=>line.replace(/^[-*+]\s+/,'').replace(/^\d+[.)]\s+/,'').replace(/^\[[ xX]\]\s*/,'').replace(/\[([^\]]+)\]\([^\)]+\)/g,'$1').replace(/[*_`>#]/g,'').replace(/\s+/g,' ').trim();
function extractRoadmapItems(text,source){if(!text)return [];const lines=text.split(/\r?\n/);let capture=false;const items=[];const sourceIsRoadmap=/roadmap|endgoal|plan/i.test(source);for(const line of lines){const heading=line.match(/^#{1,4}\s+(.+)/);if(heading){const title=clean(heading[1]);capture=/roadmap|next|priority|milestone|phase|plan|what.?s next|current/i.test(title);if(items.length&&!capture)break;continue}const bullet=line.match(/^\s*(?:[-*+] |\d+[.)] )(.+)/);if(!bullet||(!capture&&!sourceIsRoadmap))continue;const raw=bullet[1].trim(),done=/^\[[xX]\]/.test(raw),textValue=clean(raw);if(textValue&&textValue.length<=180&&!/^https?:/i.test(textValue))items.push({text:textValue,done});if(items.length>=6)break}return items}
function roadmapCandidates(harness){const explicit=(harness?.sources_of_truth||[]).filter(s=>/product|roadmap|plan|goal/i.test(s.area||'')).flatMap(s=>s.paths||[]).filter(p=>/\.md$/i.test(p));return [...new Set(['ROADMAP.md','docs/ROADMAP.md','docs/ENDGOAL.md',...explicit,'README.md'])].slice(0,7)}
async function findDerivedRoadmap(repo,harness){for(const source of roadmapCandidates(harness)){try{const text=await rawText(repo,source),items=extractRoadmapItems(text,source);if(items.length)return {standardized:false,source,achieved:items.filter(x=>x.done).map(x=>({title:x.text})),current:{title:(items.find(x=>!x.done)||items[0]).text,status:'derived'},next:items.filter(x=>!x.done).slice(0,3).map(x=>({title:x.text})),later:items.filter(x=>!x.done).slice(3).map(x=>x.text)}}catch{}}return {standardized:false,source:null,achieved:[],current:null,next:[],later:[]}}
function normalizeRoadmapContract(value){if(!value||value.schema!=='mikel-harness-roadmap-v0.1'||typeof value.north_star!=='string')return null;const normalizeMilestone=x=>typeof x==='string'?{title:x}:{title:String(x?.title||''),why:x?.why||null,evidence:Array.isArray(x?.evidence)?x.evidence:[]};return {standardized:true,source:'.harness/roadmap.json',northStar:value.north_star,achieved:(value.achieved||[]).map(normalizeMilestone).filter(x=>x.title),current:value.current&&value.current.title?{title:String(value.current.title),status:String(value.current.status||'active'),outcome:value.current.outcome||null}:null,next:(value.next||[]).map(normalizeMilestone).filter(x=>x.title).slice(0,3),later:(value.later||[]).map(x=>typeof x==='string'?x:String(x?.title||'')).filter(Boolean).slice(0,5),sources:Array.isArray(value.sources)?value.sources:[],updatedAt:value.updated_at||null}}
function commitTitle(message=''){const lines=String(message).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return null;let title=lines[0];if(/^merge pull request/i.test(title)&&lines[1])title=lines[1];if(/^merge branch/i.test(title)||/noop|pages-deploy-status/i.test(title))return null;return clean(title).slice(0,180)}
async function recentAchievements(repo){try{const rows=await request(`/repos/${repo.fullName.split('/').map(encodeURIComponent).join('/')}/commits?per_page=6`);return (Array.isArray(rows)?rows:[]).map(row=>({text:commitTitle(row.commit?.message),date:row.commit?.committer?.date||row.commit?.author?.date||null,url:row.html_url||null})).filter(x=>x.text).slice(0,3)}catch{return []}}
function compactUnique(values,limit=3){const seen=new Set(),out=[];for(const value of values){const text=clean(String(value||'')),key=text.toLowerCase();if(!text||seen.has(key)||/merge pr|merge pull request/i.test(text))continue;seen.add(key);out.push(text);if(out.length>=limit)break}return out}
function makeBrief(repo,harness,task,road,achievements,state){const isCore=corePriority.includes(repo.name),purpose=harness?.project?.purpose||repo.description||null,taskDone=task?.status==='completed';const nextWins=road.next?.length?road.next.map(x=>x.title):compactUnique([...(task&&!taskDone?[task.next_step]:[]),...(task&&!taskDone?(task.done_when||[]):[])],3);const currentGoal=road.current?.title||(task&&!taskDone?task.goal:(nextWins[0]||'Choose the next explicit product milestone.'));const currentSummary=road.current?.outcome||(task?(taskDone?'The last explicit task is complete; the roadmap now carries the product direction.':`${String(task.status||'active').replaceAll('_',' ')} · ${task.current_step||'work in progress'}`):'No explicit current task is recorded.');let statusLabel=({needs_you:'NEEDS YOU',blocked:'BLOCKED',active:'MOVING',untracked:'SETUP NEEDED',idle:'QUIET',completed:'MOVING · LAST TASK DONE'}[state.state]||String(state.state).toUpperCase());if(road.current?.status==='blocked')statusLabel='BLOCKED';let lane='quiet';if(isCore)lane='core';else if(['needs_you','blocked'].includes(state.state)||(repo.daysSincePush!==null&&repo.daysSincePush<=14))lane='active';else if(repo.daysSincePush!==null&&repo.daysSincePush<=60)lane='active';return {isCore,purpose,currentGoal,currentSummary,statusLabel,lane,achievements,nextWins,roadmap:{...road,northStar:road.northStar||purpose},evidenceNote:road.standardized?'North Star and product horizon come from .harness/roadmap.json; activity comes from GitHub and harness state.':'Roadmap is conservatively derived from repository-owned docs because no roadmap contract exists yet.'}}
function portfolioSummary(repos){return {username:owner,scope:'public-safe',count:repos.length,publicCount:repos.length,privateCount:0,active30:repos.filter(r=>r.daysSincePush!==null&&r.daysSincePush<=30).length,active90:repos.filter(r=>r.daysSincePush!==null&&r.daysSincePush<=90).length}}
function newestTimestamp(repos){const values=repos.map(r=>Date.parse(r.pushedAt||'')).filter(Number.isFinite);return new Date(values.length?Math.max(...values):Date.now()).toISOString()}

const repos=(await listPublicRepos()).map(normalize),byName=new Map(repos.map(r=>[r.name,r])),candidates=[],seen=new Set();for(const name of corePriority){const repo=byName.get(name);if(repo){candidates.push(repo);seen.add(repo.fullName)}}for(const repo of repos){if(candidates.length>=maxProjects)break;if(seen.has(repo.fullName)||repo.size===0)continue;if(repo.daysSincePush!==null&&repo.daysSincePush<=90){candidates.push(repo);seen.add(repo.fullName)}}
const projects=await mapLimit(candidates,4,async repo=>{let harness=null,task=null,contract=null,inspectionError=null;try{[harness,task,contract]=await Promise.all([readJson(repo,'.harness/project.json'),readJson(repo,'.harness/active-task.json'),readJson(repo,'.harness/roadmap.json')])}catch(error){inspectionError=error.message}const state=deriveProjectState({repo,harness,task,label:repo.name});if(inspectionError)state.uncertainties=[...(state.uncertainties||[]),inspectionError];const [derived,achievements]=await Promise.all([contract?Promise.resolve(null):findDerivedRoadmap(repo,harness),recentAchievements(repo)]);const road=normalizeRoadmapContract(contract)||derived||{standardized:false,achieved:[],current:null,next:[],later:[]};state.brief=makeBrief(repo,harness,task,road,achievements,state);if(road.current?.status==='blocked'){state.state='blocked';state.blocked=true}return state});
projects.sort((a,b)=>{if(Boolean(a.brief?.isCore)!==Boolean(b.brief?.isCore))return a.brief?.isCore?-1:1;return b.attention-a.attention||(a.daysSincePush??9999)-(b.daysSincePush??9999)||a.name.localeCompare(b.name)});const core=projects.filter(p=>p.brief?.isCore),harnessed=projects.filter(p=>p.harnessed).length,needsYou=projects.filter(p=>p.needsYou),blocked=projects.filter(p=>p.blocked),untracked=projects.filter(p=>p.state==='untracked'),top=projects.find(p=>p.attention>0)||null;
const snapshot={schema:'council-mission-control-v0.3',experienceVersion:'0.6',generatedAt:newestTimestamp(repos),mode:'github_pages_snapshot',scope:'public-safe',warning:'Public GitHub Pages intentionally publishes public repository state only. Private project details are excluded rather than leaked.',portfolio:portfolioSummary(repos),summary:{deepTracked:projects.length,harnessed,harnessCoverage:projects.length?Math.round(harnessed/projects.length*100):0,core:core.length,coreRoadmaps:core.filter(p=>p.brief?.roadmap?.standardized).length,needsYou:needsYou.length,blocked:blocked.length,untracked:untracked.length,hidden:0},topMove:top?{project:top.name,state:top.state,reason:top.reason,nextStep:top.nextStep||'Open the project and define the next explicit task contract.',repo:top.repo}:null,projects,needsYou,blocked,refresh:{workflowUrl:refreshUrl,label:'Run GitHub refresh'},evidenceModel:{observed:'Public GitHub metadata, repository harness state, recent commits and explicit .harness/roadmap.json contracts',inferred:'Secondary-project ordering and fallback roadmaps when a contract is missing'},safety:{publicSafe:true,privateDetailsPublished:false,browserSecrets:false},limitations:['v0.6 is read-only','Public Pages excludes private repository details','Only explicit .harness/roadmap.json data is treated as durable roadmap truth']};
fs.rmSync(outDir,{recursive:true,force:true});const missionDir=path.join(outDir,'mission-control');fs.mkdirSync(missionDir,{recursive:true});for(const file of ['mission-control.html','mission-control.css','mission-control.js']){const source=path.resolve('public',file),destination=path.join(missionDir,file==='mission-control.html'?'index.html':file);fs.copyFileSync(source,destination)}fs.writeFileSync(path.join(missionDir,'mission-control.json'),JSON.stringify(snapshot,null,2)+'\n');fs.writeFileSync(path.join(outDir,'.nojekyll'),'');fs.writeFileSync(path.join(outDir,'index.html'),'<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=./mission-control/"><script>location.replace("./mission-control/")</script><title>Mission Control</title>');console.log(`MISSION CONTROL PAGES PASS: ${projects.length} projects · ${core.length} core missions · ${core.filter(p=>p.brief?.roadmap?.standardized).length}/${core.length} roadmap-native.`);
